import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Navigation from '@/components/Navigation'
const inter = Inter({ subsets: ['latin'] })
import '@fontsource/roboto/300.css'
import dynamic from 'next/dynamic'

const PlotlyPlot = dynamic(() => import('../components/PlotlyPlot'), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        />
      </Head>
      <main>
        <Navigation/>
        <p className='text-secondary'>Hello, World!</p>
        <PlotlyPlot/>
      </main>
    </>
  )
}
